version: '3'
services:
  echo:
    build: .
    image: tritran14/echo-server
    environment:
      PORT: 5000
      APP_NAME: my-docker-compose-instance
      SHOW_ENVS: 1
    #ports:
    #  - 5000:5000
    restart: always
  web:
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/log/docker:/var/log/nginx
    ports:
      - 8080:8080
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']
    restart: always

